sql_scripts:
  - |
    DO $$
    BEGIN
      IF NOT EXISTS (SELECT FROM pg_catalog.pg_roles WHERE rolname = 'owner') THEN
        CREATE USER owner WITH PASSWORD 'gatostem123';
      END IF;
    END $$;
  - "GRANT ALL PRIVILEGES ON DATABASE postgres TO owner;"
  - "CREATE SCHEMA IF NOT EXISTS files;"